import type { Metadata } from "next";
import Link from "next/link";
import { ArrowRight, BarChart3, Gift, Layers3, RefreshCcw, Rocket, ShoppingBag } from "lucide-react";
import { blogPosts } from "@/lib/site-data";

export const metadata: Metadata = { title: "Practice Growth Guides", description: "Actionable Nexcore guides for launching a branded clinic app, building patient loyalty, selling treatments online, growing memberships, and reading performance.", alternates: { canonical: "/resources/guides" } };

const guides = [
  { title: "The branded app launch playbook", description: "Prepare your treatment catalog, rewards, team workflow, and first month of patient communication.", icon: Rocket, slug: "branded-clinic-app-launch", label: "Launch · 7 min" },
  { title: "The patient loyalty playbook", description: "Choose useful actions, create clear milestones, and make reward progress visible.", icon: Gift, slug: "build-a-patient-loyalty-program", label: "Loyalty · 7 min" },
  { title: "The mobile commerce playbook", description: "Structure treatment discovery, product details, checkout, and considerate follow-up.", icon: ShoppingBag, slug: "after-hours-treatment-sales", label: "Ecommerce · 6 min" },
  { title: "The membership offer playbook", description: "Shape recurring value, communicate member pricing, and support the plan after signup.", icon: RefreshCcw, slug: "membership-offer-framework", label: "Memberships · 8 min" },
  { title: "The weekly metrics playbook", description: "Connect app sales, loyalty activity, offer funnels, reviews, and referrals.", icon: BarChart3, slug: "clinic-dashboard-metrics", label: "Reporting · 6 min" },
];

export default function GuidesPage() {
  return <main id="main-content"><section className="guides-hero section-dark"><div className="section-container"><span className="eyebrow eyebrow-light"><Layers3 size={14} /> Nexcore growth guides</span><h1>Practical playbooks for a practice that stays connected.</h1><p>Step-by-step frameworks for the mobile patient journey—from preparing your app to reading what happens after launch.</p></div></section><section className="guide-list-section section-light"><div className="section-container"><div className="guide-list">{guides.map((guide, index) => { const Icon = guide.icon; return <article key={guide.slug}><span className="guide-number">0{index + 1}</span><div className="guide-icon"><Icon size={24} /></div><div><small>{guide.label}</small><h2>{guide.title}</h2><p>{guide.description}</p></div><Link href={`/resources/blog/${guide.slug}`} aria-label={`Read ${guide.title}`}><ArrowRight size={19} /></Link></article>; })}</div></div></section><section className="guide-principles section-soft"><div className="section-container"><div className="split-heading"><div><span className="eyebrow eyebrow-pink">A connected approach</span><h2>Every playbook supports the same patient journey.</h2></div><p>Help patients discover what is relevant, understand the value, act with confidence, and keep a clear reason to return.</p></div><div className="principle-grid"><div><span>01</span><h3>Be easy to find</h3><p>Keep your practice, treatment catalog, and useful information on the patient’s phone.</p></div><div><span>02</span><h3>Be easy to choose</h3><p>Organize by concern and explain treatment, package, and membership value clearly.</p></div><div><span>03</span><h3>Be worth returning to</h3><p>Use rewards, member benefits, relevant content, and a consistent branded experience.</p></div></div></div></section><section className="simple-cta section-pink"><div className="section-container"><span className="eyebrow eyebrow-light">From guide to growth</span><h2>See how these playbooks come together in Nexcore.</h2><p>Explore the branded patient app and owner dashboard in a tailored walkthrough.</p><Link className="button button-white" href="/book-demo">Book a demo <ArrowRight size={17} /></Link></div></section></main>;
}
