import type { Metadata } from "next";
import { BarChart3, Check, Gift, RefreshCcw, ShoppingBag, Smartphone, Sparkles } from "lucide-react";
import { LeadForm } from "@/components/lead-form";

export const metadata: Metadata = { title: "Book a Demo", description: "Book a tailored Nexcore demo and explore the branded patient app, treatment storefront, rewards, memberships, and owner dashboard.", alternates: { canonical: "/book-demo" } };

export default function BookDemoPage() {
  return <main id="main-content"><section className="demo-page section-dark"><div className="demo-orb one" /><div className="demo-orb two" /><div className="section-container demo-grid"><div className="demo-copy"><span className="eyebrow eyebrow-light"><Sparkles size={14} /> Personalized walkthrough</span><h1>See how Nexcore can work for your practice.</h1><p>Explore the branded patient app and owner dashboard through the growth priorities that matter most to your team.</p><ul><li><span><Smartphone size={18} /></span><div><strong>Your patient app</strong><small>Brand, treatment discovery, locations, and content</small></div></li><li><span><ShoppingBag size={18} /></span><div><strong>24/7 mobile shopping</strong><small>Treatments, packages, basket, and checkout</small></div></li><li><span><Gift size={18} /></span><div><strong>Rewards and engagement</strong><small>Points, unlocks, referrals, reviews, and offers</small></div></li><li><span><RefreshCcw size={18} /></span><div><strong>Memberships</strong><small>Recurring benefits, pricing, and treatment choices</small></div></li><li><span><BarChart3 size={18} /></span><div><strong>Owner visibility</strong><small>Sales, clients, activity, and offer reporting</small></div></li></ul><div className="demo-expect"><span>What to expect</span><p>A focused product conversation shaped around your practice type and current priorities—without a generic presentation.</p></div></div><div className="form-card demo-form-card"><div className="form-card-heading"><span>Request a demo</span><h2>Tell us about your practice.</h2><p>Share a few details so we can make your walkthrough relevant.</p></div><LeadForm /></div></div></section><section className="after-demo section-light"><div className="section-container"><div className="center-heading narrow"><span className="eyebrow eyebrow-pink">A clear next step</span><h2>Leave with a complete view of the patient and owner experience.</h2></div><div className="after-demo-grid"><article><span>01</span><Check size={20} /><h3>See the patient journey</h3><p>Follow discovery, treatment details, membership value, rewards, and checkout on mobile.</p></article><article><span>02</span><Check size={20} /><h3>Explore the dashboard</h3><p>Review the sales, client, reward, referral, review, visit, and offer views available to owners.</p></article><article><span>03</span><Check size={20} /><h3>Discuss your priorities</h3><p>Focus the walkthrough on the areas your practice most wants to improve.</p></article></div></div></section></main>;
}
